# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_ball/mb_ball.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball || ORIG_REF_NAME==mb_ball} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_microblaze_0_0/mb_ball_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_microblaze_0_0 || ORIG_REF_NAME==mb_ball_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_dlmb_v10_0/mb_ball_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_dlmb_v10_0 || ORIG_REF_NAME==mb_ball_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_ilmb_v10_0/mb_ball_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_ilmb_v10_0 || ORIG_REF_NAME==mb_ball_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_dlmb_bram_if_cntlr_0/mb_ball_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ball_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_ilmb_bram_if_cntlr_0/mb_ball_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_ball_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_lmb_bram_0/mb_ball_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_lmb_bram_0 || ORIG_REF_NAME==mb_ball_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_xbar_0/mb_ball_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_xbar_0 || ORIG_REF_NAME==mb_ball_xbar_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_microblaze_0_axi_periph_0/mb_ball_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_ball_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_microblaze_0_axi_intc_0/mb_ball_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_ball_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_mdm_1_0/mb_ball_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_mdm_1_0 || ORIG_REF_NAME==mb_ball_mdm_1_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_clk_wiz_1_0/mb_ball_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_clk_wiz_1_0 || ORIG_REF_NAME==mb_ball_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_rst_clk_wiz_1_100M_0/mb_ball_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_ball_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_uartlite_0_0/mb_ball_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ball_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_gpio_0_0/mb_ball_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_gpio_0_0 || ORIG_REF_NAME==mb_ball_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_gpio_0_1/mb_ball_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_gpio_0_1 || ORIG_REF_NAME==mb_ball_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_gpio_0_2/mb_ball_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_gpio_0_2 || ORIG_REF_NAME==mb_ball_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_timer_0_0/mb_ball_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_timer_0_0 || ORIG_REF_NAME==mb_ball_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_axi_quad_spi_0_0/mb_ball_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_ball_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_ball/ip/mb_ball_xlconcat_0_0/mb_ball_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ball_xlconcat_0_0 || ORIG_REF_NAME==mb_ball_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/mb_ball_ooc.xdc
