# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7s50csga324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/ec67/hdl
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/7698
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/ip/clk_wiz_0
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ip/mb_ball_axi_quad_spi_0_0/netlist
  } {
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/ec67/hdl
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/7698
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/ip/clk_wiz_0
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ip/mb_ball_axi_quad_spi_0_0/netlist
  } {
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Color_Mapper.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Mario.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Mario_State.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Mario_running_1ROM.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Mario_running_2ROM.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Mario_running_3ROM.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Palette_Background.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Palette_Mario.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/Smash_Background.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/VGA_controller.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/hex.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/imports/design_source/ram.sv
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.srcs/sources_1/new/SMASH_TOP.sv
    }
      rt::read_verilog -include {
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/ec67/hdl
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/7698
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/ip/clk_wiz_0
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ip/mb_ball_axi_quad_spi_0_0/netlist
  } {
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_microblaze_0_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_dlmb_v10_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_ilmb_v10_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_dlmb_bram_if_cntlr_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_ilmb_bram_if_cntlr_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_lmb_bram_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_xbar_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_microblaze_0_axi_intc_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_mdm_1_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_clk_wiz_1_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_rst_clk_wiz_1_100M_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_uartlite_0_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_gpio_0_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_gpio_0_1_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_gpio_0_2_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_timer_0_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/mb_ball_axi_quad_spi_0_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/clk_wiz_0_stub.v
      C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/realtime/hdmi_tx_0_stub.v
      c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/synth/mb_ball.v
    }
      rt::read_verilog -include {
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/ec67/hdl
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/7698
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/ip/clk_wiz_0
    c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ip/mb_ball_axi_quad_spi_0_0/netlist
  } {
      c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v
      c:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.gen/sources_1/bd/mb_ball/ip/mb_ball_xlconcat_0_0/synth/mb_ball_xlconcat_0_0.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top SMASH_TOP
    rt::set_parameter incrementalOnCache "C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Git_Smash/ECE385_Smash/Smash_Bros/Smash_Bros.runs/synth_1/.Xil/Vivado-6864-DESKTOP-MTC1J3G/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
